export type SourceDef = {
  id: string;
  name: string;
  category: "government" | "airline" | "transport" | "news";
  url: string;
  parser: "rss" | "html";
  connector: "rss" | "direct_html" | "api";
  fallback_connector?: "chrome_relay";
  extractor_id:
    | "rss_default"
    | "html_title_text"
    | "emirates_updates"
    | "etihad_updates"
    | "omanair_updates"
    | "rta_news"
    | "mofa_news"
    | "visit_dubai_articles"
    | "india_mea_press"
    | "india_boi_home"
    | "flydubai_updates"
    | "air_arabia_updates"
    | "qatar_airways_updates"
    | "gcaa_news";
  priority: number;
  freshness_target_minutes: number;
  x_handles?: string[];
  region: string;
};

export const PROJECT_NAME = "Gulf Corridor Watch";

export const OFFICIAL_SOURCES: SourceDef[] = [
  {
    id: "us_state_dept_travel",
    name: "US State Dept Travel Advisories",
    category: "government",
    url: "https://travel.state.gov/_res/rss/TAsTWs.xml",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 80,
    freshness_target_minutes: 15,
    region: "Global/US",
  },
  {
    id: "white_house_statements",
    name: "White House Statements & Releases",
    category: "government",
    url: "https://www.whitehouse.gov/briefing-room/statements-releases/feed/",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 92,
    freshness_target_minutes: 10,
    x_handles: ["POTUS", "WhiteHouse"],
    region: "US / Middle East posture",
  },
  {
    id: "us_dod_releases",
    name: "US Department of Defense Releases",
    category: "government",
    url: "https://www.defense.gov/News/Releases/RSS/",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 91,
    freshness_target_minutes: 10,
    x_handles: ["DeptofDefense"],
    region: "US / Regional security",
  },
  {
    id: "us_centcom_news",
    name: "US CENTCOM News",
    category: "government",
    url: "https://www.centcom.mil/MEDIA/NEWS-ARTICLES/News-Article-View/RSS/",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 93,
    freshness_target_minutes: 10,
    x_handles: ["CENTCOM"],
    region: "Middle East security",
  },
  {
    id: "uae_mofa",
    name: "UAE Ministry of Foreign Affairs",
    category: "government",
    url: "https://www.mofa.gov.ae/en/mediahub/news",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "mofa_news",
    priority: 88,
    freshness_target_minutes: 10,
    x_handles: ["mofauae"],
    region: "UAE",
  },
  {
    id: "visit_dubai_news",
    name: "Dubai Government / Visit Dubai News",
    category: "government",
    url: "https://www.mediaoffice.ae/en/news",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "visit_dubai_articles",
    priority: 55,
    freshness_target_minutes: 15,
    region: "Dubai",
  },
  {
    id: "emirates_updates",
    name: "Emirates Travel Updates",
    category: "airline",
    url: "https://www.emirates.com/ae/english/help/travel-updates/",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "emirates_updates",
    priority: 100,
    freshness_target_minutes: 5,
    x_handles: ["emirates"],
    region: "UAE",
  },
  {
    id: "etihad_advisory",
    name: "Etihad Travel Alerts",
    category: "airline",
    url: "https://www.etihad.com/en/help/travel-updates",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "etihad_updates",
    priority: 98,
    freshness_target_minutes: 5,
    x_handles: ["etihad"],
    region: "UAE",
  },
  {
    id: "oman_air",
    name: "Oman Air Travel Updates",
    category: "airline",
    url: "https://www.omanair.com/om/en/travel-updates",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "omanair_updates",
    priority: 70,
    freshness_target_minutes: 10,
    region: "Oman",
  },
  {
    id: "rta_dubai",
    name: "Dubai Transport & Road News (The National)",
    category: "transport",
    url: "https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 90,
    freshness_target_minutes: 5,
    x_handles: ["rta_dubai"],
    region: "Dubai",
  },
  {
    id: "india_mea",
    name: "India MEA Advisories",
    category: "government",
    url: "https://mea.gov.in/press-releases.htm?51/Press_Releases=",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "india_mea_press",
    priority: 65,
    freshness_target_minutes: 15,
    region: "India",
  },
  {
    id: "india_immigration_boi",
    name: "India Bureau of Immigration",
    category: "government",
    url: "https://boi.gov.in/boi",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "india_boi_home",
    priority: 72,
    freshness_target_minutes: 15,
    region: "India",
  },
  {
    id: "flydubai_updates",
    name: "flydubai Travel Updates",
    category: "airline",
    url: "https://www.flydubai.com/en/travel-updates",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "flydubai_updates",
    priority: 95,
    freshness_target_minutes: 5,
    x_handles: ["flydubai"],
    region: "UAE",
  },
  {
    id: "air_arabia_updates",
    name: "Air Arabia Travel Updates",
    category: "airline",
    url: "https://www.airarabia.com/en/travel-alerts",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "air_arabia_updates",
    priority: 85,
    freshness_target_minutes: 10,
    x_handles: ["aaboriginal"],
    region: "UAE",
  },
  {
    id: "qatar_airways_updates",
    name: "Qatar Airways Travel Alerts",
    category: "airline",
    url: "https://www.qatarairways.com/en/travel-alerts.html",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "html_title_text",
    priority: 80,
    freshness_target_minutes: 10,
    region: "Qatar (transit via Doha)",
  },
  {
    id: "gcaa_uae",
    name: "UAE General Civil Aviation Authority",
    category: "government",
    url: "https://www.gcaa.gov.ae/en/pages/newslist.aspx",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "html_title_text",
    priority: 96,
    freshness_target_minutes: 5,
    x_handles: ["ABORJALUAE"],
    region: "UAE",
  },
  {
    id: "uk_fcdo_uae",
    name: "UK FCDO Travel Advice — UAE",
    category: "government",
    url: "https://www.gov.uk/foreign-travel-advice/united-arab-emirates.atom",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 75,
    freshness_target_minutes: 15,
    region: "UK / UAE",
  },
  {
    id: "australia_dfat_uae",
    name: "Australian DFAT SmartTraveller — UAE",
    category: "government",
    url: "https://www.smartraveller.gov.au/destinations/middle-east/united-arab-emirates",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "html_title_text",
    priority: 60,
    freshness_target_minutes: 30,
    region: "Australia / UAE",
  },
  {
    id: "canada_gac_uae",
    name: "Canadian GAC Travel Advice — UAE",
    category: "government",
    url: "https://travel.gc.ca/destinations/united-arab-emirates",
    parser: "html",
    connector: "direct_html",
    fallback_connector: "chrome_relay",
    extractor_id: "html_title_text",
    priority: 58,
    freshness_target_minutes: 30,
    region: "Canada / UAE",
  },
  {
    id: "gn_uae_flights",
    name: "Google News: UAE Flights",
    category: "news",
    url: "https://news.google.com/rss/search?q=UAE+flights+suspended+cancelled&hl=en-GB&gl=GB&ceid=GB:en",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 55,
    freshness_target_minutes: 10,
    region: "UAE",
  },
  {
    id: "gn_gulf_conflict",
    name: "Google News: Gulf Conflict",
    category: "news",
    url: "https://news.google.com/rss/search?q=Iran+war+Gulf+UAE+airspace&hl=en-GB&gl=GB&ceid=GB:en",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 55,
    freshness_target_minutes: 10,
    region: "Gulf region",
  },
  {
    id: "gn_strait_hormuz",
    name: "Google News: Strait of Hormuz",
    category: "news",
    url: "https://news.google.com/rss/search?q=Strait+Hormuz+shipping+flights&hl=en-GB&gl=GB&ceid=GB:en",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 50,
    freshness_target_minutes: 15,
    region: "Gulf region",
  },
  {
    id: "gn_dubai_airport",
    name: "Google News: Dubai Airport",
    category: "news",
    url: "https://news.google.com/rss/search?q=Dubai+airport+DXB+open+closed&hl=en-GB&gl=GB&ceid=GB:en",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 55,
    freshness_target_minutes: 10,
    region: "Dubai",
  },
  {
    id: "gn_india_dubai_travel",
    name: "Google News: India-Dubai Travel",
    category: "news",
    url: "https://news.google.com/rss/search?q=India+UAE+flights+advisory+travel&hl=en-GB&gl=GB&ceid=GB:en",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 45,
    freshness_target_minutes: 15,
    region: "India / UAE",
  },
  {
    id: "bbc_middle_east",
    name: "BBC News: Middle East",
    category: "news",
    url: "https://feeds.bbci.co.uk/news/world/middle_east/rss.xml",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 60,
    freshness_target_minutes: 10,
    region: "Middle East",
  },
  {
    id: "aljazeera_news",
    name: "Al Jazeera News",
    category: "news",
    url: "https://www.aljazeera.com/xml/rss/all.xml",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 58,
    freshness_target_minutes: 10,
    region: "Global / Middle East",
  },
  {
    id: "uk_fcdo_iran",
    name: "UK FCDO Travel Advice — Iran",
    category: "news",
    url: "https://www.gov.uk/foreign-travel-advice/iran.atom",
    parser: "rss",
    connector: "rss",
    extractor_id: "rss_default",
    priority: 70,
    freshness_target_minutes: 15,
    region: "UK / Iran",
  },
];
